/********************************************************************************
** Form generated from reading UI file 'dlgfullkeyboard.ui'
**
** Created by: Qt User Interface Compiler version 5.3.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_DLGFULLKEYBOARD_H
#define UI_DLGFULLKEYBOARD_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDialog>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_CDlgFullKeyboard
{
public:
    QWidget *widgetEdit;
    QWidget *widgetKeyboard;
    QGroupBox *groupBox_2;
    QPushButton *btnA;
    QPushButton *btnB;
    QPushButton *btnC;
    QPushButton *btnD;
    QPushButton *btnG;
    QPushButton *btnE;
    QPushButton *btnF;
    QPushButton *btnH;
    QPushButton *btnJ;
    QPushButton *btnI;
    QPushButton *btnM;
    QPushButton *btnK;
    QPushButton *btnL;
    QPushButton *btnP;
    QPushButton *btnR;
    QPushButton *btnN;
    QPushButton *btnS;
    QPushButton *btnO;
    QPushButton *btnT;
    QPushButton *btnQ;
    QPushButton *btnW;
    QPushButton *btn_At;
    QPushButton *btnX;
    QPushButton *btnU;
    QPushButton *btnY;
    QPushButton *btn_Dash;
    QPushButton *btnPeriod;
    QPushButton *btnZ;
    QPushButton *btnV;
    QPushButton *btn_Underscore;
    QPushButton *btn_Semicolon;
    QPushButton *btn_Ampersand;
    QPushButton *btn_Dollar;
    QPushButton *btn_Plus;
    QPushButton *btn_Colon;
    QPushButton *btn_Apostrophe;
    QPushButton *btn_Quote;
    QPushButton *btn_QuestionMark;
    QPushButton *btn_Slash;
    QPushButton *btn_Splat;
    QPushButton *btn_LeftParen;
    QPushButton *btn_Exclamation;
    QPushButton *btn_Pound;
    QPushButton *btn_Percent;
    QPushButton *btn_RightParen;
    QPushButton *btn_Caret;
    QPushButton *btn_0;
    QPushButton *btn_7;
    QPushButton *btn_Space;
    QPushButton *btn_9;
    QPushButton *btn_5;
    QPushButton *btn_1;
    QPushButton *btn_3;
    QPushButton *btn_6;
    QPushButton *btn_Return;
    QPushButton *btn_8;
    QPushButton *btn_2;
    QPushButton *btn_4;
    QPushButton *btn_Back;
    QPushButton *btn_Del;
    QPushButton *btn_Close;
    QPushButton *btn_Clear;
    QPushButton *btn_LeftSquare;
    QPushButton *btn_LeftCurly;
    QPushButton *btn_RightSquare;
    QPushButton *btn_Back_Slash;
    QPushButton *btn_LeftAngle;
    QPushButton *btn_Tilde;
    QPushButton *btn_RightAngle;
    QPushButton *btn_RightCurly;
    QPushButton *btn_OpenApost;
    QPushButton *btn_Upper_Lower;
    QLabel *lblCurrentEditFieldName;
    QLineEdit *edText;

    void setupUi(QDialog *CDlgFullKeyboard)
    {
        if (CDlgFullKeyboard->objectName().isEmpty())
            CDlgFullKeyboard->setObjectName(QStringLiteral("CDlgFullKeyboard"));
        CDlgFullKeyboard->resize(800, 480);
        QFont font;
        font.setPointSize(15);
        CDlgFullKeyboard->setFont(font);
        widgetEdit = new QWidget(CDlgFullKeyboard);
        widgetEdit->setObjectName(QStringLiteral("widgetEdit"));
        widgetEdit->setEnabled(true);
        widgetEdit->setGeometry(QRect(0, 0, 800, 480));
        widgetEdit->setFont(font);
        widgetKeyboard = new QWidget(widgetEdit);
        widgetKeyboard->setObjectName(QStringLiteral("widgetKeyboard"));
        widgetKeyboard->setGeometry(QRect(0, 119, 800, 361));
        widgetKeyboard->setFont(font);
        widgetKeyboard->setFocusPolicy(Qt::NoFocus);
        groupBox_2 = new QGroupBox(widgetKeyboard);
        groupBox_2->setObjectName(QStringLiteral("groupBox_2"));
        groupBox_2->setEnabled(true);
        groupBox_2->setGeometry(QRect(10, -10, 781, 371));
        groupBox_2->setFont(font);
        btnA = new QPushButton(groupBox_2);
        btnA->setObjectName(QStringLiteral("btnA"));
        btnA->setGeometry(QRect(0, 17, 55, 55));
        btnA->setFont(font);
        btnA->setFocusPolicy(Qt::NoFocus);
        btnB = new QPushButton(groupBox_2);
        btnB->setObjectName(QStringLiteral("btnB"));
        btnB->setGeometry(QRect(60, 17, 55, 55));
        btnB->setFont(font);
        btnB->setFocusPolicy(Qt::NoFocus);
        btnC = new QPushButton(groupBox_2);
        btnC->setObjectName(QStringLiteral("btnC"));
        btnC->setGeometry(QRect(120, 17, 55, 55));
        btnC->setFont(font);
        btnC->setFocusPolicy(Qt::NoFocus);
        btnD = new QPushButton(groupBox_2);
        btnD->setObjectName(QStringLiteral("btnD"));
        btnD->setGeometry(QRect(180, 17, 55, 55));
        btnD->setFont(font);
        btnD->setFocusPolicy(Qt::NoFocus);
        btnG = new QPushButton(groupBox_2);
        btnG->setObjectName(QStringLiteral("btnG"));
        btnG->setGeometry(QRect(360, 17, 55, 55));
        btnG->setFont(font);
        btnG->setFocusPolicy(Qt::NoFocus);
        btnE = new QPushButton(groupBox_2);
        btnE->setObjectName(QStringLiteral("btnE"));
        btnE->setGeometry(QRect(240, 17, 55, 55));
        btnE->setFont(font);
        btnE->setFocusPolicy(Qt::NoFocus);
        btnF = new QPushButton(groupBox_2);
        btnF->setObjectName(QStringLiteral("btnF"));
        btnF->setGeometry(QRect(300, 17, 55, 55));
        btnF->setFont(font);
        btnF->setFocusPolicy(Qt::NoFocus);
        btnH = new QPushButton(groupBox_2);
        btnH->setObjectName(QStringLiteral("btnH"));
        btnH->setGeometry(QRect(420, 17, 55, 55));
        btnH->setFont(font);
        btnH->setFocusPolicy(Qt::NoFocus);
        btnJ = new QPushButton(groupBox_2);
        btnJ->setObjectName(QStringLiteral("btnJ"));
        btnJ->setGeometry(QRect(540, 17, 55, 55));
        btnJ->setFont(font);
        btnJ->setFocusPolicy(Qt::NoFocus);
        btnI = new QPushButton(groupBox_2);
        btnI->setObjectName(QStringLiteral("btnI"));
        btnI->setGeometry(QRect(480, 17, 55, 55));
        btnI->setFont(font);
        btnI->setFocusPolicy(Qt::NoFocus);
        btnM = new QPushButton(groupBox_2);
        btnM->setObjectName(QStringLiteral("btnM"));
        btnM->setGeometry(QRect(120, 77, 55, 55));
        btnM->setFont(font);
        btnM->setFocusPolicy(Qt::NoFocus);
        btnK = new QPushButton(groupBox_2);
        btnK->setObjectName(QStringLiteral("btnK"));
        btnK->setGeometry(QRect(0, 77, 55, 55));
        btnK->setFont(font);
        btnK->setFocusPolicy(Qt::NoFocus);
        btnL = new QPushButton(groupBox_2);
        btnL->setObjectName(QStringLiteral("btnL"));
        btnL->setGeometry(QRect(60, 77, 55, 55));
        btnL->setFont(font);
        btnL->setFocusPolicy(Qt::NoFocus);
        btnP = new QPushButton(groupBox_2);
        btnP->setObjectName(QStringLiteral("btnP"));
        btnP->setGeometry(QRect(300, 77, 55, 55));
        btnP->setFont(font);
        btnP->setFocusPolicy(Qt::NoFocus);
        btnR = new QPushButton(groupBox_2);
        btnR->setObjectName(QStringLiteral("btnR"));
        btnR->setGeometry(QRect(420, 77, 55, 55));
        btnR->setFont(font);
        btnR->setFocusPolicy(Qt::NoFocus);
        btnN = new QPushButton(groupBox_2);
        btnN->setObjectName(QStringLiteral("btnN"));
        btnN->setGeometry(QRect(180, 77, 55, 55));
        btnN->setFont(font);
        btnN->setFocusPolicy(Qt::NoFocus);
        btnS = new QPushButton(groupBox_2);
        btnS->setObjectName(QStringLiteral("btnS"));
        btnS->setGeometry(QRect(480, 77, 55, 55));
        btnS->setFont(font);
        btnS->setFocusPolicy(Qt::NoFocus);
        btnO = new QPushButton(groupBox_2);
        btnO->setObjectName(QStringLiteral("btnO"));
        btnO->setGeometry(QRect(240, 77, 55, 55));
        btnO->setFont(font);
        btnO->setFocusPolicy(Qt::NoFocus);
        btnT = new QPushButton(groupBox_2);
        btnT->setObjectName(QStringLiteral("btnT"));
        btnT->setGeometry(QRect(540, 77, 55, 55));
        btnT->setFont(font);
        btnT->setFocusPolicy(Qt::NoFocus);
        btnQ = new QPushButton(groupBox_2);
        btnQ->setObjectName(QStringLiteral("btnQ"));
        btnQ->setGeometry(QRect(360, 77, 55, 55));
        btnQ->setFont(font);
        btnQ->setFocusPolicy(Qt::NoFocus);
        btnW = new QPushButton(groupBox_2);
        btnW->setObjectName(QStringLiteral("btnW"));
        btnW->setGeometry(QRect(120, 136, 55, 55));
        btnW->setFont(font);
        btnW->setFocusPolicy(Qt::NoFocus);
        btn_At = new QPushButton(groupBox_2);
        btn_At->setObjectName(QStringLiteral("btn_At"));
        btn_At->setGeometry(QRect(360, 136, 55, 55));
        btn_At->setFont(font);
        btn_At->setFocusPolicy(Qt::NoFocus);
        btnX = new QPushButton(groupBox_2);
        btnX->setObjectName(QStringLiteral("btnX"));
        btnX->setGeometry(QRect(180, 136, 55, 55));
        btnX->setFont(font);
        btnX->setFocusPolicy(Qt::NoFocus);
        btnU = new QPushButton(groupBox_2);
        btnU->setObjectName(QStringLiteral("btnU"));
        btnU->setGeometry(QRect(0, 136, 55, 55));
        btnU->setFont(font);
        btnU->setFocusPolicy(Qt::NoFocus);
        btnY = new QPushButton(groupBox_2);
        btnY->setObjectName(QStringLiteral("btnY"));
        btnY->setGeometry(QRect(240, 136, 55, 55));
        btnY->setFont(font);
        btnY->setFocusPolicy(Qt::NoFocus);
        btn_Dash = new QPushButton(groupBox_2);
        btn_Dash->setObjectName(QStringLiteral("btn_Dash"));
        btn_Dash->setGeometry(QRect(540, 136, 55, 55));
        btn_Dash->setFont(font);
        btn_Dash->setFocusPolicy(Qt::NoFocus);
        btnPeriod = new QPushButton(groupBox_2);
        btnPeriod->setObjectName(QStringLiteral("btnPeriod"));
        btnPeriod->setGeometry(QRect(420, 136, 55, 55));
        btnPeriod->setFont(font);
        btnPeriod->setFocusPolicy(Qt::NoFocus);
        btnZ = new QPushButton(groupBox_2);
        btnZ->setObjectName(QStringLiteral("btnZ"));
        btnZ->setGeometry(QRect(300, 136, 55, 55));
        btnZ->setFont(font);
        btnZ->setFocusPolicy(Qt::NoFocus);
        btnV = new QPushButton(groupBox_2);
        btnV->setObjectName(QStringLiteral("btnV"));
        btnV->setGeometry(QRect(60, 136, 55, 55));
        btnV->setFont(font);
        btnV->setFocusPolicy(Qt::NoFocus);
        btn_Underscore = new QPushButton(groupBox_2);
        btn_Underscore->setObjectName(QStringLiteral("btn_Underscore"));
        btn_Underscore->setGeometry(QRect(480, 136, 55, 55));
        btn_Underscore->setFont(font);
        btn_Underscore->setFocusPolicy(Qt::NoFocus);
        btn_Semicolon = new QPushButton(groupBox_2);
        btn_Semicolon->setObjectName(QStringLiteral("btn_Semicolon"));
        btn_Semicolon->setGeometry(QRect(240, 196, 55, 55));
        btn_Semicolon->setFont(font);
        btn_Semicolon->setFocusPolicy(Qt::NoFocus);
        btn_Ampersand = new QPushButton(groupBox_2);
        btn_Ampersand->setObjectName(QStringLiteral("btn_Ampersand"));
        btn_Ampersand->setGeometry(QRect(480, 196, 55, 55));
        btn_Ampersand->setFont(font);
        btn_Ampersand->setFocusPolicy(Qt::NoFocus);
        btn_Dollar = new QPushButton(groupBox_2);
        btn_Dollar->setObjectName(QStringLiteral("btn_Dollar"));
        btn_Dollar->setGeometry(QRect(540, 196, 55, 55));
        btn_Dollar->setFont(font);
        btn_Dollar->setFocusPolicy(Qt::NoFocus);
        btn_Plus = new QPushButton(groupBox_2);
        btn_Plus->setObjectName(QStringLiteral("btn_Plus"));
        btn_Plus->setGeometry(QRect(0, 196, 55, 55));
        btn_Plus->setFont(font);
        btn_Plus->setFocusPolicy(Qt::NoFocus);
        btn_Colon = new QPushButton(groupBox_2);
        btn_Colon->setObjectName(QStringLiteral("btn_Colon"));
        btn_Colon->setGeometry(QRect(180, 196, 55, 55));
        btn_Colon->setFont(font);
        btn_Colon->setFocusPolicy(Qt::NoFocus);
        btn_Apostrophe = new QPushButton(groupBox_2);
        btn_Apostrophe->setObjectName(QStringLiteral("btn_Apostrophe"));
        btn_Apostrophe->setGeometry(QRect(300, 196, 55, 55));
        btn_Apostrophe->setFont(font);
        btn_Apostrophe->setFocusPolicy(Qt::NoFocus);
        btn_Quote = new QPushButton(groupBox_2);
        btn_Quote->setObjectName(QStringLiteral("btn_Quote"));
        btn_Quote->setGeometry(QRect(360, 196, 55, 55));
        btn_Quote->setFont(font);
        btn_Quote->setFocusPolicy(Qt::NoFocus);
        btn_QuestionMark = new QPushButton(groupBox_2);
        btn_QuestionMark->setObjectName(QStringLiteral("btn_QuestionMark"));
        btn_QuestionMark->setGeometry(QRect(60, 196, 55, 55));
        btn_QuestionMark->setFont(font);
        btn_QuestionMark->setFocusPolicy(Qt::NoFocus);
        btn_Slash = new QPushButton(groupBox_2);
        btn_Slash->setObjectName(QStringLiteral("btn_Slash"));
        btn_Slash->setGeometry(QRect(120, 196, 55, 55));
        btn_Slash->setFont(font);
        btn_Slash->setFocusPolicy(Qt::NoFocus);
        btn_Splat = new QPushButton(groupBox_2);
        btn_Splat->setObjectName(QStringLiteral("btn_Splat"));
        btn_Splat->setGeometry(QRect(420, 196, 55, 55));
        btn_Splat->setFont(font);
        btn_Splat->setFocusPolicy(Qt::NoFocus);
        btn_LeftParen = new QPushButton(groupBox_2);
        btn_LeftParen->setObjectName(QStringLiteral("btn_LeftParen"));
        btn_LeftParen->setGeometry(QRect(660, 196, 55, 55));
        btn_LeftParen->setFont(font);
        btn_LeftParen->setFocusPolicy(Qt::NoFocus);
        btn_Exclamation = new QPushButton(groupBox_2);
        btn_Exclamation->setObjectName(QStringLiteral("btn_Exclamation"));
        btn_Exclamation->setGeometry(QRect(600, 136, 55, 55));
        btn_Exclamation->setFont(font);
        btn_Exclamation->setFocusPolicy(Qt::NoFocus);
        btn_Pound = new QPushButton(groupBox_2);
        btn_Pound->setObjectName(QStringLiteral("btn_Pound"));
        btn_Pound->setGeometry(QRect(660, 136, 55, 55));
        btn_Pound->setFont(font);
        btn_Pound->setFocusPolicy(Qt::NoFocus);
        btn_Percent = new QPushButton(groupBox_2);
        btn_Percent->setObjectName(QStringLiteral("btn_Percent"));
        btn_Percent->setGeometry(QRect(600, 196, 55, 55));
        btn_Percent->setFont(font);
        btn_Percent->setFocusPolicy(Qt::NoFocus);
        btn_RightParen = new QPushButton(groupBox_2);
        btn_RightParen->setObjectName(QStringLiteral("btn_RightParen"));
        btn_RightParen->setGeometry(QRect(720, 196, 55, 55));
        btn_RightParen->setFont(font);
        btn_RightParen->setFocusPolicy(Qt::NoFocus);
        btn_Caret = new QPushButton(groupBox_2);
        btn_Caret->setObjectName(QStringLiteral("btn_Caret"));
        btn_Caret->setGeometry(QRect(720, 136, 55, 55));
        btn_Caret->setFont(font);
        btn_Caret->setFocusPolicy(Qt::NoFocus);
        btn_0 = new QPushButton(groupBox_2);
        btn_0->setObjectName(QStringLiteral("btn_0"));
        btn_0->setGeometry(QRect(0, 314, 55, 55));
        btn_0->setFont(font);
        btn_0->setFocusPolicy(Qt::NoFocus);
        btn_7 = new QPushButton(groupBox_2);
        btn_7->setObjectName(QStringLiteral("btn_7"));
        btn_7->setGeometry(QRect(420, 314, 55, 55));
        btn_7->setFont(font);
        btn_7->setFocusPolicy(Qt::NoFocus);
        btn_Space = new QPushButton(groupBox_2);
        btn_Space->setObjectName(QStringLiteral("btn_Space"));
        btn_Space->setGeometry(QRect(600, 314, 91, 55));
        QFont font1;
        font1.setPointSize(12);
        btn_Space->setFont(font1);
        btn_Space->setFocusPolicy(Qt::NoFocus);
        btn_9 = new QPushButton(groupBox_2);
        btn_9->setObjectName(QStringLiteral("btn_9"));
        btn_9->setGeometry(QRect(540, 314, 55, 55));
        btn_9->setFont(font);
        btn_9->setFocusPolicy(Qt::NoFocus);
        btn_5 = new QPushButton(groupBox_2);
        btn_5->setObjectName(QStringLiteral("btn_5"));
        btn_5->setGeometry(QRect(300, 314, 55, 55));
        btn_5->setFont(font);
        btn_5->setFocusPolicy(Qt::NoFocus);
        btn_1 = new QPushButton(groupBox_2);
        btn_1->setObjectName(QStringLiteral("btn_1"));
        btn_1->setGeometry(QRect(60, 314, 55, 55));
        btn_1->setFont(font);
        btn_1->setFocusPolicy(Qt::NoFocus);
        btn_3 = new QPushButton(groupBox_2);
        btn_3->setObjectName(QStringLiteral("btn_3"));
        btn_3->setGeometry(QRect(180, 314, 55, 55));
        btn_3->setFont(font);
        btn_3->setFocusPolicy(Qt::NoFocus);
        btn_6 = new QPushButton(groupBox_2);
        btn_6->setObjectName(QStringLiteral("btn_6"));
        btn_6->setGeometry(QRect(360, 314, 55, 55));
        btn_6->setFont(font);
        btn_6->setFocusPolicy(Qt::NoFocus);
        btn_Return = new QPushButton(groupBox_2);
        btn_Return->setObjectName(QStringLiteral("btn_Return"));
        btn_Return->setGeometry(QRect(694, 314, 81, 55));
        btn_Return->setFont(font1);
        btn_Return->setFocusPolicy(Qt::NoFocus);
        btn_8 = new QPushButton(groupBox_2);
        btn_8->setObjectName(QStringLiteral("btn_8"));
        btn_8->setGeometry(QRect(480, 314, 55, 55));
        btn_8->setFont(font);
        btn_8->setFocusPolicy(Qt::NoFocus);
        btn_2 = new QPushButton(groupBox_2);
        btn_2->setObjectName(QStringLiteral("btn_2"));
        btn_2->setGeometry(QRect(120, 314, 55, 55));
        btn_2->setFont(font);
        btn_2->setFocusPolicy(Qt::NoFocus);
        btn_4 = new QPushButton(groupBox_2);
        btn_4->setObjectName(QStringLiteral("btn_4"));
        btn_4->setGeometry(QRect(240, 314, 55, 55));
        btn_4->setFont(font);
        btn_4->setFocusPolicy(Qt::NoFocus);
        btn_Back = new QPushButton(groupBox_2);
        btn_Back->setObjectName(QStringLiteral("btn_Back"));
        btn_Back->setGeometry(QRect(600, 17, 91, 55));
        btn_Back->setFont(font1);
        btn_Back->setFocusPolicy(Qt::NoFocus);
        btn_Del = new QPushButton(groupBox_2);
        btn_Del->setObjectName(QStringLiteral("btn_Del"));
        btn_Del->setGeometry(QRect(600, 78, 91, 55));
        btn_Del->setFont(font1);
        btn_Del->setFocusPolicy(Qt::NoFocus);
        btn_Close = new QPushButton(groupBox_2);
        btn_Close->setObjectName(QStringLiteral("btn_Close"));
        btn_Close->setGeometry(QRect(696, 17, 80, 55));
        btn_Close->setFont(font1);
        btn_Close->setFocusPolicy(Qt::NoFocus);
        btn_Clear = new QPushButton(groupBox_2);
        btn_Clear->setObjectName(QStringLiteral("btn_Clear"));
        btn_Clear->setGeometry(QRect(695, 78, 80, 55));
        btn_Clear->setFont(font1);
        btn_Clear->setFocusPolicy(Qt::NoFocus);
        btn_LeftSquare = new QPushButton(groupBox_2);
        btn_LeftSquare->setObjectName(QStringLiteral("btn_LeftSquare"));
        btn_LeftSquare->setGeometry(QRect(540, 254, 55, 55));
        btn_LeftSquare->setFont(font);
        btn_LeftSquare->setFocusPolicy(Qt::NoFocus);
        btn_LeftCurly = new QPushButton(groupBox_2);
        btn_LeftCurly->setObjectName(QStringLiteral("btn_LeftCurly"));
        btn_LeftCurly->setGeometry(QRect(420, 254, 55, 55));
        btn_LeftCurly->setFont(font);
        btn_LeftCurly->setFocusPolicy(Qt::NoFocus);
        btn_RightSquare = new QPushButton(groupBox_2);
        btn_RightSquare->setObjectName(QStringLiteral("btn_RightSquare"));
        btn_RightSquare->setGeometry(QRect(600, 254, 55, 55));
        btn_RightSquare->setFont(font);
        btn_RightSquare->setFocusPolicy(Qt::NoFocus);
        btn_Back_Slash = new QPushButton(groupBox_2);
        btn_Back_Slash->setObjectName(QStringLiteral("btn_Back_Slash"));
        btn_Back_Slash->setGeometry(QRect(120, 254, 55, 55));
        btn_Back_Slash->setFont(font);
        btn_Back_Slash->setFocusPolicy(Qt::NoFocus);
        btn_LeftAngle = new QPushButton(groupBox_2);
        btn_LeftAngle->setObjectName(QStringLiteral("btn_LeftAngle"));
        btn_LeftAngle->setGeometry(QRect(300, 254, 55, 55));
        btn_LeftAngle->setFont(font);
        btn_LeftAngle->setFocusPolicy(Qt::NoFocus);
        btn_Tilde = new QPushButton(groupBox_2);
        btn_Tilde->setObjectName(QStringLiteral("btn_Tilde"));
        btn_Tilde->setGeometry(QRect(240, 254, 55, 55));
        btn_Tilde->setFont(font);
        btn_Tilde->setFocusPolicy(Qt::NoFocus);
        btn_RightAngle = new QPushButton(groupBox_2);
        btn_RightAngle->setObjectName(QStringLiteral("btn_RightAngle"));
        btn_RightAngle->setGeometry(QRect(360, 254, 55, 55));
        btn_RightAngle->setFont(font);
        btn_RightAngle->setFocusPolicy(Qt::NoFocus);
        btn_RightCurly = new QPushButton(groupBox_2);
        btn_RightCurly->setObjectName(QStringLiteral("btn_RightCurly"));
        btn_RightCurly->setGeometry(QRect(480, 254, 55, 55));
        btn_RightCurly->setFont(font);
        btn_RightCurly->setFocusPolicy(Qt::NoFocus);
        btn_OpenApost = new QPushButton(groupBox_2);
        btn_OpenApost->setObjectName(QStringLiteral("btn_OpenApost"));
        btn_OpenApost->setGeometry(QRect(180, 254, 55, 55));
        btn_OpenApost->setFont(font);
        btn_OpenApost->setFocusPolicy(Qt::NoFocus);
        btn_Upper_Lower = new QPushButton(groupBox_2);
        btn_Upper_Lower->setObjectName(QStringLiteral("btn_Upper_Lower"));
        btn_Upper_Lower->setGeometry(QRect(660, 254, 111, 55));
        btn_Upper_Lower->setFont(font1);
        btn_Upper_Lower->setFocusPolicy(Qt::NoFocus);
        btn_Upper_Lower->setCheckable(true);
        btn_Upper_Lower->setChecked(false);
        lblCurrentEditFieldName = new QLabel(widgetEdit);
        lblCurrentEditFieldName->setObjectName(QStringLiteral("lblCurrentEditFieldName"));
        lblCurrentEditFieldName->setGeometry(QRect(20, 20, 411, 21));
        lblCurrentEditFieldName->setFont(font);
        edText = new QLineEdit(widgetEdit);
        edText->setObjectName(QStringLiteral("edText"));
        edText->setGeometry(QRect(10, 50, 771, 71));
        edText->setFont(font1);
        edText->setMouseTracking(false);
        edText->setAcceptDrops(false);
        edText->setInputMethodHints(Qt::ImhHiddenText|Qt::ImhNoAutoUppercase|Qt::ImhNoPredictiveText|Qt::ImhSensitiveData);

        retranslateUi(CDlgFullKeyboard);

        QMetaObject::connectSlotsByName(CDlgFullKeyboard);
    } // setupUi

    void retranslateUi(QDialog *CDlgFullKeyboard)
    {
        CDlgFullKeyboard->setWindowTitle(QApplication::translate("CDlgFullKeyboard", "Dialog", 0));
        groupBox_2->setTitle(QString());
        btnA->setText(QApplication::translate("CDlgFullKeyboard", "A", 0));
        btnB->setText(QApplication::translate("CDlgFullKeyboard", "B", 0));
        btnC->setText(QApplication::translate("CDlgFullKeyboard", "C", 0));
        btnD->setText(QApplication::translate("CDlgFullKeyboard", "D", 0));
        btnG->setText(QApplication::translate("CDlgFullKeyboard", "G", 0));
        btnE->setText(QApplication::translate("CDlgFullKeyboard", "E", 0));
        btnF->setText(QApplication::translate("CDlgFullKeyboard", "F", 0));
        btnH->setText(QApplication::translate("CDlgFullKeyboard", "H", 0));
        btnJ->setText(QApplication::translate("CDlgFullKeyboard", "J", 0));
        btnI->setText(QApplication::translate("CDlgFullKeyboard", "I", 0));
        btnM->setText(QApplication::translate("CDlgFullKeyboard", "M", 0));
        btnK->setText(QApplication::translate("CDlgFullKeyboard", "K", 0));
        btnL->setText(QApplication::translate("CDlgFullKeyboard", "L", 0));
        btnP->setText(QApplication::translate("CDlgFullKeyboard", "P", 0));
        btnR->setText(QApplication::translate("CDlgFullKeyboard", "R", 0));
        btnN->setText(QApplication::translate("CDlgFullKeyboard", "N", 0));
        btnS->setText(QApplication::translate("CDlgFullKeyboard", "S", 0));
        btnO->setText(QApplication::translate("CDlgFullKeyboard", "O", 0));
        btnT->setText(QApplication::translate("CDlgFullKeyboard", "T", 0));
        btnQ->setText(QApplication::translate("CDlgFullKeyboard", "Q", 0));
        btnW->setText(QApplication::translate("CDlgFullKeyboard", "W", 0));
        btn_At->setText(QApplication::translate("CDlgFullKeyboard", "@", 0));
        btnX->setText(QApplication::translate("CDlgFullKeyboard", "X", 0));
        btnU->setText(QApplication::translate("CDlgFullKeyboard", "U", 0));
        btnY->setText(QApplication::translate("CDlgFullKeyboard", "Y", 0));
        btn_Dash->setText(QApplication::translate("CDlgFullKeyboard", "-", 0));
        btnPeriod->setText(QApplication::translate("CDlgFullKeyboard", ".", 0));
        btnZ->setText(QApplication::translate("CDlgFullKeyboard", "Z", 0));
        btnV->setText(QApplication::translate("CDlgFullKeyboard", "V", 0));
        btn_Underscore->setText(QApplication::translate("CDlgFullKeyboard", "_", 0));
        btn_Semicolon->setText(QApplication::translate("CDlgFullKeyboard", ";", 0));
        btn_Ampersand->setText(QApplication::translate("CDlgFullKeyboard", "&&", 0));
        btn_Dollar->setText(QApplication::translate("CDlgFullKeyboard", "$", 0));
        btn_Plus->setText(QApplication::translate("CDlgFullKeyboard", "+", 0));
        btn_Colon->setText(QApplication::translate("CDlgFullKeyboard", ":", 0));
        btn_Apostrophe->setText(QApplication::translate("CDlgFullKeyboard", "'", 0));
        btn_Quote->setText(QApplication::translate("CDlgFullKeyboard", "\"", 0));
        btn_QuestionMark->setText(QApplication::translate("CDlgFullKeyboard", "?", 0));
        btn_Slash->setText(QApplication::translate("CDlgFullKeyboard", "/", 0));
        btn_Splat->setText(QApplication::translate("CDlgFullKeyboard", "*", 0));
        btn_LeftParen->setText(QApplication::translate("CDlgFullKeyboard", "(", 0));
        btn_Exclamation->setText(QApplication::translate("CDlgFullKeyboard", "!", 0));
        btn_Pound->setText(QApplication::translate("CDlgFullKeyboard", "#", 0));
        btn_Percent->setText(QApplication::translate("CDlgFullKeyboard", "%", 0));
        btn_RightParen->setText(QApplication::translate("CDlgFullKeyboard", ")", 0));
        btn_Caret->setText(QApplication::translate("CDlgFullKeyboard", "^", 0));
        btn_0->setText(QApplication::translate("CDlgFullKeyboard", "0", 0));
        btn_7->setText(QApplication::translate("CDlgFullKeyboard", "7", 0));
        btn_Space->setText(QApplication::translate("CDlgFullKeyboard", "Space", 0));
        btn_9->setText(QApplication::translate("CDlgFullKeyboard", "9", 0));
        btn_5->setText(QApplication::translate("CDlgFullKeyboard", "5", 0));
        btn_1->setText(QApplication::translate("CDlgFullKeyboard", "1", 0));
        btn_3->setText(QApplication::translate("CDlgFullKeyboard", "3", 0));
        btn_6->setText(QApplication::translate("CDlgFullKeyboard", "6", 0));
        btn_Return->setText(QApplication::translate("CDlgFullKeyboard", "Enter", 0));
        btn_8->setText(QApplication::translate("CDlgFullKeyboard", "8", 0));
        btn_2->setText(QApplication::translate("CDlgFullKeyboard", "2", 0));
        btn_4->setText(QApplication::translate("CDlgFullKeyboard", "4", 0));
        btn_Back->setText(QApplication::translate("CDlgFullKeyboard", "Back", 0));
        btn_Del->setText(QApplication::translate("CDlgFullKeyboard", "Del", 0));
        btn_Close->setText(QApplication::translate("CDlgFullKeyboard", "Close", 0));
        btn_Clear->setText(QApplication::translate("CDlgFullKeyboard", "Clear", 0));
        btn_LeftSquare->setText(QApplication::translate("CDlgFullKeyboard", "[", 0));
        btn_LeftCurly->setText(QApplication::translate("CDlgFullKeyboard", "{", 0));
        btn_RightSquare->setText(QApplication::translate("CDlgFullKeyboard", "]", 0));
        btn_Back_Slash->setText(QApplication::translate("CDlgFullKeyboard", "\\", 0));
        btn_LeftAngle->setText(QApplication::translate("CDlgFullKeyboard", "<", 0));
        btn_Tilde->setText(QApplication::translate("CDlgFullKeyboard", "~", 0));
        btn_RightAngle->setText(QApplication::translate("CDlgFullKeyboard", ">", 0));
        btn_RightCurly->setText(QApplication::translate("CDlgFullKeyboard", "}", 0));
        btn_OpenApost->setText(QApplication::translate("CDlgFullKeyboard", "`", 0));
        btn_Upper_Lower->setText(QApplication::translate("CDlgFullKeyboard", "Lower", 0));
        lblCurrentEditFieldName->setText(QApplication::translate("CDlgFullKeyboard", "TextLabel", 0));
    } // retranslateUi

};

namespace Ui {
    class CDlgFullKeyboard: public Ui_CDlgFullKeyboard {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_DLGFULLKEYBOARD_H
